#!/bin/bash
# Build minimal Buildroot rootfs for RISC-V QEMU using external toolchain
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/env.sh"

# Configuration options
DO_MENUCONFIG=false
DO_DEFCONFIG=false
DO_CLEAN=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --menuconfig)
            DO_MENUCONFIG=true
            shift
            ;;
        --defconfig)
            DO_DEFCONFIG=true
            shift
            ;;
        --clean)
            DO_CLEAN=true
            shift
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo "  Build Buildroot rootfs for RISC-V QEMU"
            echo ""
            echo "Options:"
            echo "  --menuconfig  Run menuconfig only (exit after)"
            echo "  --defconfig   Force create default config (even if .config exists)"
            echo "  --clean       Run make clean before building"
            echo "  -h, --help    Show this help message"
            echo ""
            echo "Default behavior:"
            echo "  - If .config exists, skip creating default config"
            echo "  - If .config does not exist, create default config"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

COMPONENT="buildroot"
LOG_FILE="${LOG_DIR}/${COMPONENT}-$(date +%Y%m%d-%H%M%S).log"

echo "=== Building Buildroot Rootfs ==="
echo "Source: ${BUILDROOT_SRC}"
echo "Output: ${ROOTFS_BUILD}"
echo "Log: ${LOG_FILE}"

mkdir -p "${ROOTFS_BUILD}" "${LOG_DIR}"

cd "${BUILDROOT_SRC}"

# Clean build if requested
if [ "${DO_CLEAN}" = true ]; then
    echo "[Buildroot] Running make clean..."
    make O="${ROOTFS_BUILD}" clean >> "${LOG_FILE}" 2>&1
fi

# Determine if we need to create config
RUN_DEFCONFIG=false
if [ "${DO_DEFCONFIG}" = true ]; then
    RUN_DEFCONFIG=true
    echo "[Buildroot] Force defconfig requested..."
elif [ ! -f "${ROOTFS_BUILD}/.config" ]; then
    RUN_DEFCONFIG=true
    echo "[Buildroot] No .config found, creating default config..."
else
    echo "[Buildroot] Using existing .config..."
fi

# Create base config if needed
if [ "${RUN_DEFCONFIG}" = true ]; then
    # NOTE: We intentionally expand ${BUILD_DIR} here to point Buildroot's
    # BR2_ROOTFS_OVERLAY at a generated overlay under ./build/.
    cat > "${ROOTFS_BUILD}/.config" << EOF
# Target architecture
BR2_riscv=y
BR2_RISCV_64=y
BR2_RISCV_ABI_LP64D=y

# Use external toolchain from host
BR2_TOOLCHAIN_EXTERNAL=y
BR2_TOOLCHAIN_EXTERNAL_DOWNLOAD=y
BR2_TOOLCHAIN_EXTERNAL_BOOTLIN=y
BR2_TOOLCHAIN_EXTERNAL_BOOTLIN_RISCV64_GLIBC_STABLE=y

# System configuration
BR2_TARGET_GENERIC_HOSTNAME="buildroot"
BR2_TARGET_GENERIC_ISSUE="Welcome to RISC-V Buildroot"
BR2_SYSTEM_DHCP="eth0"
BR2_TARGET_GENERIC_GETTY=y
BR2_TARGET_GENERIC_GETTY_PORT="console"

# Init system
BR2_INIT_BUSYBOX=y

# Root filesystem - CPIO for initramfs
BR2_TARGET_ROOTFS_CPIO=y
BR2_TARGET_ROOTFS_CPIO_GZIP=y

# Rootfs overlay (generated by scripts/build_worldguard_tests.sh)
BR2_ROOTFS_OVERLAY="${BUILD_DIR}/rootfs-overlay"

# No kernel (built separately)
BR2_LINUX_KERNEL=n
EOF

    echo "[Buildroot] Running olddefconfig..."
    make O="${ROOTFS_BUILD}" olddefconfig >> "${LOG_FILE}" 2>&1
fi

# Menuconfig mode
if [ "${DO_MENUCONFIG}" = true ]; then
    echo "[Buildroot] Running menuconfig..."
    make O="${ROOTFS_BUILD}" menuconfig
    echo "[Buildroot] menuconfig complete. Exiting."
    exit 0
fi

# Build rootfs
echo "[Buildroot] Building with ${NPROC} jobs..."
make O="${ROOTFS_BUILD}" -j${NPROC} >> "${LOG_FILE}" 2>&1

echo "[Buildroot] Build complete!"

# Check for output
if [ -f "${ROOTFS_BUILD}/images/rootfs.cpio.gz" ]; then
    echo "Rootfs: ${ROOTFS_BUILD}/images/rootfs.cpio.gz"
    echo "[Buildroot] SUCCESS"
    exit 0
elif [ -f "${ROOTFS_BUILD}/images/rootfs.cpio" ]; then
    echo "Rootfs: ${ROOTFS_BUILD}/images/rootfs.cpio"
    echo "[Buildroot] SUCCESS"
    exit 0
else
    echo "[Buildroot] ERROR: Rootfs not found"
    ls -la "${ROOTFS_BUILD}/images/" 2>/dev/null || true
    exit 1
fi
